baseURL: "https://seminario-nogales2023.netlify.app/"
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - robotsTXT
defaultContentLanguage: en
theme: hugo-scroll
title: Precios de vivienda como determinantes de migración interna. un análisis a escala de área metropolitana
params:
  copyright: © José Luis Manzanares Rivera
  description: El Colef Unidad Nogales
  favicon: images/favicon.png
  hidedesignbyline: no
  images: images/pexels-pixabay.jpg
  invertSectionColors: no
  meta:
    keywords: Projecto Affordable Housing on border cities.  
  title: Precios de vivienda como determinantes de migración interna. un análisis a escala de área metropolitana
  title_guard: no
