baseURL: https://seminario-nogales-2023.netlify.app/
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - robotsTXT
defaultContentLanguage: en
theme: hugo-scroll
title: Jane Doe - Nutrition Coach & Chef Consultant
params:
  copyright: © Jane Doe
  description: Nutrition Coach & Chef Consultant
  favicon: images/favicon.png
  hidedesignbyline: no
  images: images/pexels-pixabay.jpg
  invertSectionColors: no
  meta:
    keywords: some, keywords, for, seo, you, know, google, duckduckgo, and, such
  title: Precios de vivienda como determinantes de migración interna. un análisis a escala de área metropolitana
  title_guard: no
